"""added users.py file

Revision ID: 0439a15f11bf
Revises: 2af5c8e05119
Create Date: 2024-02-06 22:03:44.524783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0439a15f11bf'
down_revision = '2af5c8e05119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name', table_name='categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    # ### end Alembic commands ###
