"""Added id's

Revision ID: 0bbd24fab300
Revises: 3dfd3be9362f
Create Date: 2024-01-29 22:35:17.729081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbd24fab300'
down_revision = '3dfd3be9362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
