"""Description of migration

Revision ID: 56e3beffaeaa
Revises: 0439a15f11bf
Create Date: 2024-02-06 22:22:34.671433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e3beffaeaa'
down_revision = '0439a15f11bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('username', sa.String(), nullable=True))
    op.drop_index('ix_tasks_name', table_name='tasks')
    op.create_index(op.f('ix_tasks_username'), 'tasks', ['username'], unique=False)
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_tasks_username'), table_name='tasks')
    op.create_index('ix_tasks_name', 'tasks', ['name'], unique=False)
    op.drop_column('tasks', 'username')
    # ### end Alembic commands ###
