"""deleted category description

Revision ID: 760832cad0b1
Revises: 0bbd24fab300
Create Date: 2024-02-06 20:29:33.596144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760832cad0b1'
down_revision = '0bbd24fab300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_description', table_name='categories')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.create_index('ix_categories_description', 'categories', ['description'], unique=False)
    # ### end Alembic commands ###
