"""Changed name to username

Revision ID: c58f48a62a98
Revises: 4c065a9a95b6
Create Date: 2024-02-06 23:27:35.022558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c58f48a62a98'
down_revision: Union[str, None] = '4c065a9a95b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


 def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###